### ISSUE TITLE
Code Syntax Highlighting

### ISSUE THREAD

**Issue by iepstein01** [seanwcom/Red-Graphite-for-Obsidian#1]
I'm very interested in using this Red Graphite theme in Obsidian,
but when I make code blocks, there is no syntax highlighting at all.

**Comment by ericaxu** [comment]
@iepstein01 Did you specify the language after the first set of backticks?

**Comment by iepstein01** [comment]
I seem to have neglected to specify the language. I didn't know that this was how it was done until after I opened up this issue. Thanks for letting me know how. 

I just wanted to say that I love the theme and will be closing the issue now.
