### ISSUE TITLE
Hover state of buttons is default purple color

### ISSUE THREAD

**Issue by ryanpcmcquen** [seanwcom/Red-Graphite-for-Obsidian#13]
Thank you for this awesome theme. I've noticed that buttons turn to the purple color on hover. Is this intentional?
<img width="306" alt="Screen Shot 2021-05-30 at 10 38 12 AM" src="https://user-images.githubusercontent.com/772937/120114467-28172e00-c134-11eb-8850-0ded00d6c8d6.png">

**Comment by timlawson-uk** [comment]
Hi @ryanpcmcquen , did this issue get corrected in the theme? Thanks.

**Comment by ryanpcmcquen** [comment]
No, my PR is still open.

**Comment by seanwcom** [comment]
Hey all, sorry for the long absence. My wife, one of my kids, and myself had Covid back in July, and we've been building a house, so its been a bit hectic. 😄  I merged that PR, so that should close this issue. I'll start taking a look at the other issues as well.
