### ISSUE TITLE
v1.0 updates have made Dark Theme border text difficult to read

### ISSUE THREAD

**Issue by kandyman2017** [seanwcom/Red-Graphite-for-Obsidian#18]
Since the Obsidian v1.0 update, I am having trouble reading the text in borders (headers) or seeing the icons in the header part of the page. The white font is quite dull and does not contrast well with the black background of the Dark Theme anymore - this makes it difficult to read or make out the icons.
![Capture](https://user-images.githubusercontent.com/32620963/196012997-ead8a312-7189-4eef-83e7-8b21c5bb28ab.JPG)

While it may not look like much of an issue from the screenshot, on a real monitor I have noticed a big different since the update.

**Comment by kandyman2017** [comment]
Additional issue related to the same update.
The left portion of text in some windows is now cut off, as in the screenshot below.

![Capture2](https://user-images.githubusercontent.com/32620963/196013599-e3547181-a06f-4e8e-8319-96a033cf76f1.JPG)

**Comment by seanwcom** [comment]
@kandyman2017 - I have updated the theme to be compatible with the 1.0 release of obsidian. This is a complete rewrite and because I don't have much time for updates, I've tried to simplify things and have really made this mostly a UI theme rather than adjusting any text.
