### ISSUE TITLE
v1.0 Obsidian upgrade truncates some filenames in file listing

### ISSUE THREAD

**Issue by chrisbunch** [seanwcom/Red-Graphite-for-Obsidian#19]
Some but not all file/folder names in the file list sidebar are missing the first few characters. See screenshot
<img width="203" alt="Screen Shot 2022-10-22 at 17 05 40" src="https://user-images.githubusercontent.com/18265982/197350217-b6148d87-95be-44e7-a479-aa753b339d01.png">

**Comment by seanwcom** [comment]
@chrisbunch - I have updated the theme to be compatible with the 1.0 release of obsidian. This is a complete rewrite and because I don't have much time for updates, I've tried to simplify things and have really made this mostly a UI theme rather than adjusting any text.

**Comment by chrisbunch** [comment]
Thank you!

Chris
________________________
