### ISSUE TITLE
Lists (ordered and unordered) don't have accent color

### ISSUE THREAD

**Issue by VadymBoikov** [seanwcom/Red-Graphite-for-Obsidian#22]
Checkboxes do have accent color, while lists are grey 

<img width="215" alt="image" src="https://user-images.githubusercontent.com/11488038/205464337-252790f2-b16b-4466-a17a-647b7fc18b80.png">

**Comment by seanwcom** [comment]
Thanks for the feedback, good catch. I've added the accent color to the bullets now which does look a lot better. The update should appear soon. Thanks!
