### ISSUE TITLE
Kanban board colors are messed up

### ISSUE THREAD

**Issue by pavlexander** [seanwcom/Red-Graphite-for-Obsidian#23]
Hi,

Could you please look into **Kanban board** plugin compatibility, when the **Light** theme is selected? Currently it does not look very appealing, and the heading text not seen at all.

Here is the example with the **Dark** theme

![image](https://user-images.githubusercontent.com/20644772/207290313-d3b1cda9-94f5-4b2e-9ec9-a42c3ca8e1ab.png)

And here's how the same board looks like in **Light** mode

![image](https://user-images.githubusercontent.com/20644772/207290380-b4939e9b-b869-44e6-b0cc-77e8fdda41ea.png)

I am no expert in design, but from the user perspective this just does not fit right.. 
The horizontal white lines are too exposed and the card titles are missing.. Could you please check if it's something that could be improved without affecting other places of the light theme of Red Graphite?

**Comment by kandyman2017** [comment]
I have the same issue with the Red Graphite theme

**Comment by seanwcom** [comment]
Thanks for the feedback, I've made a first pass at supporting Kanban. This isn't what I'd consider "full support" by any means, but it should at least be usable now. The update should show up soon. Thanks!

**Comment by kandyman2017** [comment]
Just wondering if there have been updates on this issue.
