### ISSUE TITLE
Invisible Text with Calendar Plugin (plus theme browse screen) on Light mode

### ISSUE THREAD

**Issue by ruddthree** [seanwcom/Red-Graphite-for-Obsidian#24]
I'm using the Calendar plugin, and the calendar is almost completely invisible while using the Light mode. This is also exhibited on the Theme Browsing screen, where the "show only installed" and "light/dark themes only"

![Red Graphite Light Theme Issue 1](https://user-images.githubusercontent.com/40322512/210297509-964b79a8-67ef-4ace-a4f3-509bf8865ec7.JPG)
![Red Graphite Light Theme Issue 2](https://user-images.githubusercontent.com/40322512/210297510-ffbdc13f-0456-40cd-9e65-ac7702d192c8.JPG)

**Comment by seanwcom** [comment]
I've made a first pass at supporting this and fixing up the invisible text elsewhere. It should appear as an update for the theme soon. Thanks!
