### ISSUE TITLE
Bold text is not shown as bold

### ISSUE THREAD

**Issue by mgunal** [seanwcom/Red-Graphite-for-Obsidian#25]
In Obsidian Version 1.1.9 (Installer 0.14.6) on MacOS 13.1 bold texts **like this** is not bold.

**Comment by seanwcom** [comment]
Interesting - on Windows it looks ok. I'll check it on my Mac as well. But here's what I see in Windows:

![image](https://user-images.githubusercontent.com/128131/213479142-c590b197-d5b1-4ab7-aacb-7a4fcd7fc698.png)

**Comment by mgunal** [comment]
It seems the text is actually bold but 'Avenir Next' font somehow makes the bold text unnoticeably bold (like 1px bold, hard to noticed by an untrained eye)
I changed the Text Font to 'Avenir' using Style Settings plugin. I can see the bold text in MacOS now.
It looks like a font issue to me.

**Comment by seanwcom** [comment]
Good catch, I can't recall why I chose Avenir Next, so I just changed the default to Avenir. Maybe a new issue will come in now that reminds me why I chose Next. Haha... Thanks!
