### ISSUE TITLE
White sidebar on iOS app

### ISSUE THREAD

**Issue by artsmolin** [seanwcom/Red-Graphite-for-Obsidian#26]
Thank you for the best Obsidian theme. I noticed one flaw: in the mobile version, the sidebar has a white background color in the light theme. Because of this, it is difficult to see the words. It would be very nice if you could make the background as dark as in the desktop version.
![IMAGE 2023-03-24 01:31:17](https://user-images.githubusercontent.com/17912407/227379209-5be94c7e-8e91-4d3f-a4d5-d59875637597.jpg)

**Comment by kuestess** [comment]
@artsmolin I'm far from a CSS expert but was able to get the sidebar to the correct color by creating a snippet with the content below.  Wasn't able to get the header to change color however.

```
.workspace-drawer-active-tab-container {
	background: #292c2e;
}
```
