### ISSUE TITLE
Alignment in callouts are off

### ISSUE THREAD

**Issue by mortenjust** [seanwcom/Red-Graphite-for-Obsidian#28]
Actual: The text is aligned to the top rather than center or baseline

<img width="363" alt="Screenshot 2023-08-04 at 8 45 53 AM" src="https://github.com/seanwcom/Red-Graphite-for-Obsidian/assets/1548468/af5bfd9c-8224-466b-b6b1-bf054ebf6432">

Expected ([source](https://help.obsidian.md/Editing+and+formatting/Callouts))
<img width="169" alt="Screenshot 2023-08-04 at 8 46 36 AM" src="https://github.com/seanwcom/Red-Graphite-for-Obsidian/assets/1548468/ba10c739-95dd-460c-a1bc-9c7af31c3b72">

**Comment by seanwcom** [comment]
I've compared the alignment of callouts with the default theme that ships with Obsidian and they appear the same to me.
