### ISSUE TITLE
text color is blended with the background color

### ISSUE THREAD

**Issue by yangcht** [seanwcom/Red-Graphite-for-Obsidian#3]
![bug](https://user-images.githubusercontent.com/806801/90159920-0ee8f080-dd5f-11ea-8469-c145831789b7.png)

Version: Obsidian v0.8.4 (insider)

**Comment by seanwcom** [comment]
Thanks for the issue - not sure why it didn't send me a notification, will have to look into that. Should be all set now though.

**Comment by benf101** [comment]
I'm new to this theme and have this issue today (March 2023). I don't think it's resolved.

This is by far the best theme Obsidian has, but this one bug makes it unusable in light mode. I hope to see it repaired. Thanks!
