### ISSUE TITLE
Text same color as background when using Obsidian plug-in Copilot

### ISSUE THREAD

**Issue by NTaravati** [seanwcom/Red-Graphite-for-Obsidian#33]
The sidebar text color is the same color as the background, when using the [Copilot plug-in ](https://github.com/logancyang/obsidian-copilot)for Obsidian.

<img width="946" alt="Screenshot_1" src="https://github.com/seanwcom/Red-Graphite-for-Obsidian/assets/9073800/9f4e60ba-541e-4e3f-98b8-230c21be7155">

**Comment by seanwcom** [comment]
I've just gone thru and implemented many fixes, and I've also added support for the Copilot plugin in the latest release.
