### ISSUE TITLE
Solution for the text color of the menu items is blended with the background color. Red Graphite theme and MAKE.MD plugin

### ISSUE THREAD

**Issue by MaksimZinovev** [seanwcom/Red-Graphite-for-Obsidian#34]
Here is my solution for the issue where text color of the menu items is blended with the background color when I hover over menu items. 
Theme: dark theme of Red Graphite.
Plugin: MakeMD

Issue:

<img src="https://github.com/seanwcom/Red-Graphite-for-Obsidian/assets/53397443/c98e3c92-07de-4f95-b4b7-d42dc071bb64" alt="image" width="300" class="image">

Fix: 

<img src="https://github.com/seanwcom/Red-Graphite-for-Obsidian/assets/53397443/cd527607-3c81-429e-9a91-714e6a495bfa" alt="image" width="300" class="my-image">

Solution:

```css

.mk-menu .menu-item:hover:not(.is-disabled):not(.is-label) {
  color: #ffffff;
}
```

Save this css snippet in snippet.css file and put it in your  snippets  folder `/.obsidian/snippets`. 
Go to Settings > Appearance > CSS Snippets > enable your snippet.

**Comment by MaksimZinovev** [comment]
@seanwcom would it be possible to fix this in the theme? 

thanks

**Comment by seanwcom** [comment]
I've just gone thru and implemented many fixes, and I've also added support for the Make.md plugin. I don't use this plugin though, so its kind of a "best effort" at support. Let me know if something else shows up.
