### ISSUE TITLE
Theme doesnt play nice with the daily stats plugin

### ISSUE THREAD

**Issue by NastyFlytrap** [seanwcom/Red-Graphite-for-Obsidian#35]
Specifically, the plugin adds a new tab, which is supposed to have a rectangle for every day, and instead all of them are invisible or coloured the same as the background, unless i hover over it, in which case it'll highlight the one im hovering over.

**Comment by seanwcom** [comment]
I've just released a new version with many updates. I checked on the daily stats plugin but it appears to be working for me. But I've only got a single day's worth of data in it so far. I'll keep the plugin enabled and check back in a while to see how it looks with many days worth of data.
