### ISSUE TITLE
Graphview in Pane not readable

### ISSUE THREAD

**Issue by FriedrichStein** [seanwcom/Red-Graphite-for-Obsidian#6]
Hey SeanWcom, 

love your theme for Obsidian!
The only issue I have is, that the graphview in the pane displays the text in the same color as the background.
This makes it not readable. 

Could you change that? 

![Bildschirmfoto 2021-01-01 um 18 04 16](https://user-images.githubusercontent.com/53973194/103443142-7515d780-4c5c-11eb-94d4-c70bd16a855f.jpg)

**Comment by strangemonad** [comment]
+1 love the theme but the labels on the local graph aren't rendered (0.9.x and 0.10.x)

**Comment by seanwcom** [comment]
Hey all - sorry about that, and sorry for the delay. Will get this updated later this evening. For some reason Github is not sending me notifications like it should. :)

**Comment by seanwcom** [comment]
@FriedrichStein and @strangemonad, this should be updated now. I couldn't easily find a way to do different theming for `.graph-view` in the sidebar vs in a normal pane, so instead I picked a middle gray color that shows up well regardless of light or dark background. Hopefully that works well for you. I'm seeing some really nice themes out there lately, so I'm hoping to find time to do some updates to Red Graphite in the future. :)
